/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package org.selfkleptomaniac.org.mod.tiaudiomanager;

import android.app.Activity;
import android.content.Context;
import android.media.AudioManager;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;

import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name="Tiaudiomanager", id="org.selfkleptomaniac.org.mod.tiaudiomanager")
public class TiaudiomanagerModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "TiaudiomanagerModule";
	
	@Kroll.constant
	public static final int STREAM_RING = AudioManager.STREAM_RING;
	@Kroll.constant
	public static final int STREAM_NOTIFICATION = AudioManager.STREAM_NOTIFICATION;
	@Kroll.constant
	public static final int STREAM_SYSTEM = AudioManager.STREAM_SYSTEM;
	@Kroll.constant
	public static final int STREAM_VOICE_CALL = AudioManager.STREAM_VOICE_CALL;
	@Kroll.constant
	public static final int STREAM_MUSIC = AudioManager.STREAM_MUSIC;
	@Kroll.constant
	public static final int STREAM_ALARM = AudioManager.STREAM_ALARM;
	

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TiaudiomanagerModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public int getVolume(KrollDict args){
		int streamType = Integer.valueOf(args.get("streamType").toString());
		TiApplication appContext = TiApplication.getInstance();
		Activity activity = appContext.getCurrentActivity();
		AudioManager am = (AudioManager)activity.getSystemService(Context.AUDIO_SERVICE);
		return am.getStreamVolume(streamType);
	}
	
	@Kroll.method
	public void setVolume(KrollDict args){
		int streamType = Integer.valueOf(args.get("streamType").toString());
		int volume = Integer.valueOf(args.get("volume").toString());
		TiApplication appContext = TiApplication.getInstance();
		Activity activity = appContext.getCurrentActivity();
		AudioManager am = (AudioManager)activity.getSystemService(Context.AUDIO_SERVICE);
		am.setStreamVolume(streamType, volume, AudioManager.FLAG_SHOW_UI);
	}

}

